// === Анонимное бронирование через JSONBin ===
const JSONBIN_ID = '6a099030250b1311c361f2b5';
const JSONBIN_KEY = '$2a$10$i/lit6KKQrdJZ3FYZSf.b.2LipvqwbUTCWSG7yQIrECha8/EZx6C.';

// === Сборы — общая ссылка на перевод в Т-Банк ===
const TBANK_URL = 'https://www.tbank.ru/cf/4cS9QDSyPTm';

// === Большие хочулики ===
const WISHES = [
  {
    id: 'kisses',
    title: 'Поцелуи в щёчку',
    subtitle: 'без счёта',
    note: 'Сколько хош!',
    type: 'sweet',
    image: 'assets/kisses.jpg',
    reservable: false,
    favorite: true,
  },
  {
    id: 'stories',
    title: 'Сторис обо мне',
    subtitle: 'с нашей фотой',
    note: 'Выложи нашу фотку и подпиши: «Кайфуля самая любимая подружка!»',
    type: 'social',
    image: 'assets/stories.svg',
    reservable: false,
    favorite: true,
  },
  {
    id: 'spider-robot',
    title: 'Танец робота-паука!',
    subtitle: 'я хочу его увидеть',
    note: 'Дополнительно начислю очки уважения!',
    type: 'sweet',
    image: 'assets/spider-robot.svg',
    reservable: false,
    favorite: true,
  },
  {
    id: 'botsad',
    title: 'Сводить меня в Ботанический сад',
    subtitle: '',
    note: 'Я очень давно там не была...',
    type: 'experience',
    image: 'assets/botsad.svg',
    reservable: true,
    favorite: true,
  },
  {
    id: 'cap',
    title: 'Кепка «кайфуля»',
    subtitle: 'травяного цвета · с вышивкой',
    note: 'Очень хочу кепку травяного цвета с вышивкой «кайфуля!»',
    type: 'gift',
    price: null,
    link: null,
    image: 'assets/cap.svg',
    reservable: true,
    favorite: true,
  },
  {
    id: 'macstand',
    title: 'Подставка под мак',
    subtitle: 'любая · чтобы спина сказала спасибо',
    note: 'Сижу за маком часами. Хочу поднять экран на уровень глаз.',
    type: 'gift',
    price: null,
    link: 'https://thesweetsetup.com/twelve-south-curve-laptop-stand/',
    image: 'assets/macstand.svg',
    reservable: true,
    favorite: true,
  },
  {
    id: 'card',
    title: 'Открытка от руки',
    subtitle: 'сколько угодно',
    note: 'Я буду хранить их всю жизнь! Пусть будет много — без брони.',
    type: 'gift',
    price: null,
    link: null,
    image: 'assets/card.webp',
    reservable: false,
    favorite: true,
  },

  // === По вашему желанию ===
  {
    id: 'reab',
    title: 'Сбор на лечение',
    subtitle: 'собираю деньги на реабилитацию',
    note: 'Я раздробила себе два позвонка и сломала все кости в организме. Восстановилась, но до сих пор хромаю.',
    type: 'collect',
    target: 30000,
    raised: 0,
    payment: { method: 'Т-Банк', url: TBANK_URL },
    link: 'https://bubnovsky.org/spb/prices/',
    image: 'assets/reab.jpg',
    reservable: false,
  },
  {
    id: 'cape',
    title: 'Кейп с капюшоном',
    subtitle: 'VintageDresses · сбор',
    note: 'Накидка вместо пальто, с фибулой и большим капюшоном. Как будто из другого века.',
    type: 'collect',
    target: 28000,
    raised: 0,
    payment: { method: 'Т-Банк', url: TBANK_URL },
    link: 'https://vintagedresses.ru/o/b99ab9/',
    image: 'assets/cape.jpg',
    reservable: false,
  },
  {
    id: 'coat',
    title: 'Пальто-трапеция',
    subtitle: 'Primula Design · зелёное · сбор',
    note: 'Шерсть с подкладом, зелёного. Хочу одно настоящее пальто, чтобы носить годами.',
    type: 'collect',
    target: 37500,
    raised: 0,
    payment: { method: 'Т-Банк', url: TBANK_URL },
    link: 'https://primuladesign.ru/shop/palto-trapeciia-v-zelenom-cvete',
    image: 'assets/coat.jpg',
    reservable: false,
  },
  {
    id: 'spf',
    title: 'Солнцезащитный стик',
    subtitle: 'TOCOBO · SPF50+ · сколько угодно',
    note: 'Рак кожи — отстой.',
    type: 'sweet',
    price: null,
    link: 'https://www.wildberries.ru/catalog/160847016/detail.aspx?size=267320337',
    image: 'assets/spf.webp',
    reservable: false,
  },
  {
    id: 'feathers',
    title: 'Перья в волосы',
    subtitle: 'PtashkaHair · 20–25 см · М',
    note: 'Натуральные, широкие. Без брони — пусть будет много, в волосах много места.',
    type: 'sweet',
    price: null,
    link: 'https://www.wildberries.ru/catalog/189472337/detail.aspx?size=310137221',
    image: 'assets/feathers.webp',
    reservable: false,
  },
  {
    id: 'detangler',
    title: 'Расчёска Tangle Teezer',
    subtitle: 'Ultimate Detangler · для кудрявых',
    note: 'Чтобы распутывать без слёз.',
    type: 'gift',
    price: null,
    link: 'https://www.wildberries.ru/catalog/248086824/detail.aspx?size=388507621',
    image: 'assets/detangler.webp',
    reservable: true,
  },
  {
    id: 'boardgame',
    title: 'Настолка на ваш вкус',
    subtitle: 'любую крутую · можно несколько',
    note: 'Подарите свою любимую — открою для себя что-то новое!',
    type: 'gift',
    price: null,
    link: null,
    image: 'assets/boardgame.svg',
    reservable: false,
  },
  {
    id: 'quoridor',
    title: 'Настольная игра «Коридор»',
    subtitle: 'Стиль Жизни · мини · 8+',
    note: 'Стратегия для вечеров с Лёшей.',
    type: 'gift',
    price: null,
    link: 'https://www.wildberries.ru/catalog/123438701/detail.aspx?size=216966915',
    image: 'assets/quoridor.webp',
    reservable: true,
  },
  {
    id: 'plates',
    title: 'Тарелки с ежиками',
    subtitle: 'Lefard · 20,5 см · 2 шт · фарфор',
    note: 'Хочу красивую посуду — даже когда ем одна.',
    type: 'gift',
    price: null,
    link: 'https://www.wildberries.ru/catalog/884134513/detail.aspx?size=1333921861',
    image: 'assets/plates.webp',
    reservable: true,
  },
  {
    id: 'blouse-para',
    title: 'Блузка нарядная оверсайз',
    subtitle: 'PARA SLOW',
    note: '',
    type: 'gift',
    price: null,
    link: 'https://www.wildberries.ru/catalog/229050850/detail.aspx?size=362017336',
    image: 'assets/blouse-para.webp',
    reservable: true,
  },
  {
    id: 'planner',
    title: 'Красивый ежедневник',
    subtitle: 'с обложкой, чтобы тянуло открывать',
    note: 'Веду от руки. Хочу такой, чтобы прям радовал.',
    type: 'gift',
    price: null,
    link: null,
    image: 'assets/planner.svg',
    reservable: true,
  },
  {
    id: 'book-gregori',
    title: 'Книга «Вечная принцесса»',
    subtitle: 'Филиппа Грегори',
    note: 'Исторический роман про Каталину Арагонскую.',
    type: 'gift',
    price: null,
    link: null,
    image: 'assets/book-gregori.jpg',
    reservable: true,
  },
  {
    id: 'litres',
    title: 'Подписка Литрес или Я.Книги',
    subtitle: 'на год',
    note: 'Обожаю читать! Это мой самый любимый способ избегания реальности!',
    type: 'gift',
    price: '~3 500 ₽',
    link: null,
    image: 'assets/litres.svg',
    reservable: true,
  },
  {
    id: 'shades',
    title: 'Тёмные очки Polaroid',
    subtitle: 'PLD 6175 · 086 · с поляризацией',
    note: 'Коричневая черепаховая оправа, зелёные линзы. От ультрафиолета.',
    type: 'gift',
    price: null,
    link: 'https://www.wildberries.ru/catalog/224381897/detail.aspx?size=355755050',
    image: 'assets/shades.webp',
    reservable: true,
  },
  {
    id: 'rope-park',
    title: 'Билет в верёвочный парк',
    subtitle: '',
    note: 'Белки живут на деревьях.',
    type: 'experience',
    price: null,
    link: null,
    image: 'assets/rope-park.svg',
    reservable: true,
  },
];
